/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package app.src.main.java.colorSwitch;

public class App {
    private static ColorSwitch game;

    public static void main(String[] args) {
        game = new ColorSwitch();
        game._init();
    }
}
